name: Continuous Integration Workflow
# Trigger the workflow on push or pull request, on main branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define environment variables
env: 
  PYTHON_VERSION: 3.9
  APP_DIR: ./

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Run linter
        run: | 
          ruff check ${{ env.APP_DIR }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: | 
          python -m pytest tests/

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build
        run: | 
          python setup.py sdist bdist_wheel
          twine check dist/*
